### ISSUE TITLE
Error on startup with Spigot 1.14

### ISSUE THREAD

**Issue by MWHunter** [kickash32/DistributedMobSpawns#1]
> [21:44:21] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-1eece4f-09a453a (MC: 1.14) (Implementing API version 1.14-R0.1-SNAPSHOT)
>[21:44:21] [Server thread/INFO]: Checking version, please wait...
[21:44:22] [Thread-11/INFO]: You are running the latest version`

>[21:41:12] [Server thread/INFO]: [DistributedMobSpawns] Enabling DistributedMobSpawns v1.0
[21:41:12] [Server thread/ERROR]: [DistributedMobSpawns] Plugin DistributedMobSpawns v1.0 has failed to register events for class me.kickash32.distributedmobspawns.MobSpawnListener because com.destroystokyo.paper.event.entity.PlayerNaturallySpawnCreaturesEvent does not exist.
[21:41:12] [Server thread/ERROR]: Error occurred while enabling DistributedMobSpawns v1.0 (Is it up to date?)
java.lang.NoSuchMethodError: org/bukkit/Server$Spigot.getSpigotConfig()Lorg/bukkit/configuration/file/YamlConfiguration; (loaded from file:/C:/Users/Hunter/OneDrive%20-%20student.rockvalleycollege.edu/Documents/spigot13/spigot-1.14.jar by sun.misc.Launcher$AppClassLoader@fccd4c91) called from class me.kickash32.distributedmobspawns.DistributedMobSpawns (loaded from file:/C:/Users/Hunter/OneDrive%20-%20student.rockvalleycollege.edu/Documents/spigot13/plugins/distributedMobSpawns.jar by org.bukkit.plugin.java.PluginClassLoader@6fb7b66f).
        at me.kickash32.distributedmobspawns.DistributedMobSpawns.onEnable(DistributedMobSpawns.java:30) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.14.jar:git-Spigot-1eece4f-09a453a]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.14.jar:git-Spigot-1eece4f-09a453a]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416) [spigot-1.14.jar:git-Spigot-1eece4f-09a453a]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458) [spigot-1.14.jar:git-Spigot-1eece4f-09a453a]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372) [spigot-1.14.jar:git-Spigot-1eece4f-09a453a]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:441) [spigot-1.14.jar:git-Spigot-1eece4f-09a453a]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258) [spigot-1.14.jar:git-Spigot-1eece4f-09a453a]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:762) [spigot-1.14.jar:git-Spigot-1eece4f-09a453a]
        at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]

**Comment by kickash32** [comment]
Fixed in latest commit and release
