### ISSUE TITLE
Task #37 for DistributedMobSpawns v2.2.1 generated an exception

### ISSUE THREAD

**Issue by neobenedict** [kickash32/DistributedMobSpawns#8]
Version v.2.2.1 spamming console with this error on 1.12.2 paper:

```[22:39:00] [Server thread/WARN]: [DMS] Task #37 for DistributedMobSpawns v2.2.1 generated an exception
java.lang.NoSuchMethodError: org.bukkit.entity.Entity.getEntitySpawnReason()Lorg/bukkit/event/entity/CreatureSpawnEvent$SpawnReason;
        at me.kickash32.distributedmobspawns.Util.wasNaturallySpawned(Util.java:154) ~[?:?]
        at me.kickash32.distributedmobspawns.Util.isNaturallySpawningAnimal(Util.java:112) ~[?:?]
        at me.kickash32.distributedmobspawns.EntityProcessor.update(EntityProcessor.java:40) ~[?:?]
        at me.kickash32.distributedmobspawns.UpdateMobCountsTask.run(UpdateMobCountsTask.java:21) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

Version v.2.2.0 also broken, one player is getting almost all of the mobs

```
>dms stats
[Distributed Mob Spawns]
Format: [world] player: #Animal/Animal_Limit* #Monster/Monster_Limit* #Ambient/Ambient_Limit* #Watermob/Watermob_Limit*
These should only be used as a reference for troubleshooting
[world] Morpion_: 82/15 472/70 0/15 0/5
[world] Key: 2/15 10/70 22/15 39/5
[world] NotPurpleWolf: 18/15 28/70 10/15 0/5
[world] 99toLife: 110/15 3/70 0/15 0/5
[world] Neobenedict: 7/15 0/70 0/15 0/5
[world] DestinySdemise: 79/15 10/70 0/15 0/5
[world] BigMacShrek: 51/15 1/70 0/15 0/5
[world] ForAllOtherUses: 21/15 1/70 0/15 0/5
[world] sirkibel: 7/15 8/70 0/15 0/5
[world] FreshTap: 74/15 0/70 0/15 0/5
[world] Alex_W_03: 3/15 2/70 0/15 0/5
[world] MYspyy: 1/15 0/70 0/15 0/5
[world] Total: 1556/180 537/840 32/180 39/60
[world_nether] JayAlve: 0/15 75/70 0/15 0/5
[world_nether] coenbastiaan: 0/15 0/70 0/15 0/5
[world_nether] Total: 0/30 84/140 0/30 0/10
[world_the_end] hiimroselover: 0/15 41/70 0/15 0/5
[world_the_end] Total: 7/15 41/70 0/15 0/5
[hub] Total: 0/0 0/0 0/0 0/0
```

**Comment by kickash32** [comment]
Please post your paper.yml here.

**Comment by neobenedict** [comment]
https://gist.github.com/neobenedict/a920def076b28a2ce0259a132df006fd

**Comment by kickash32** [comment]
Please also post the full startup log till the "done" message.

**Comment by neobenedict** [comment]
Due to the sensitive nature of startup logs, please comment when you have saved this so it can be removed.

https://gist.github.com/neobenedict/798dcac74417846c91164152015b0efa

**Comment by kickash32** [comment]
Got it, thanks.

**Comment by kickash32** [comment]
Actually could you enable verbose in the config.yml and send another one?

**Comment by neobenedict** [comment]
There's no verbose option in distributedmobspawns/config.yml

**Comment by neobenedict** [comment]
```
[12:55:10 INFO]: [DMS] Enabling DistributedMobSpawns v2.2.1
[12:55:10 INFO]: No enum constant org.bukkit.entity.EntityType.PHANTOM
[12:55:10 INFO]: [DMS] [world] mob-spawn-range/count-natural-mobs-only: 8/true Animal limit/cap: 15/15 Monster limit/cap: 70/70 Ambient limit/cap: 15/15 Watermob limit/cap: 5/5
[12:55:10 INFO]: [DMS] [world_nether] mob-spawn-range/count-natural-mobs-only: 8/true Animal limit/cap: 15/15 Monster limit/cap: 70/70 Ambient limit/cap: 15/15 Watermob limit/cap: 5/5
[12:55:10 INFO]: [DMS] [world_the_end] mob-spawn-range/count-natural-mobs-only: 8/true Animal limit/cap: 15/15 Monster limit/cap: 70/70 Ambient limit/cap: 15/15 Watermob limit/cap: 5/5
[12:55:10 INFO]: [DMS] [hub] mob-spawn-range/count-natural-mobs-only: 8/true Animal limit/cap: 15/15 Monster limit/cap: 70/70 Ambient limit/cap: 15/15 Watermob limit/cap: 5/5
```
Only changes I think

**Comment by kickash32** [comment]
Okay thanks, found the bug in the code, will be fixed next build.
